### ISSUE TITLE
Forked Extension

### ISSUE THREAD

**Issue by yannikthegenius** [Aaron-P/SimpleSearchGoogleFor#1]
Hello,

I didn't know where to write you because I'm not sure if your E-Mail in the extensions page "Support Email" is correct.

Just wanted to let you know that I forked your extension to redirect to Startpage instead of Google.
I uploaded it yesterday and the extension is approved.
If there are any problems, you can get in contact with me.

Thanks!

https://addons.mozilla.org/en-US/firefox/addon/simple-search-startpage-for/
https://github.com/yannikthegenius/SimpleSearchStartpageFor

**Comment by Aaron-P** [comment]
The email should work, but I have no issues with your forking.
